---
version: 1
disable_existing_loggers: False
formatters:
    simple:
        format: "%(asctime)s - %(levelname)s - [%(filename)s:%(lineno)d:%(funcName)s] - - %(message)s" #thread #http://blog.csdn.net/yatere/article/details/6655445

handlers:
    console:
        class: logging.StreamHandler
        level: DEBUG
        formatter: simple
        stream: ext://sys.stdout

    info_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: INFO
        formatter: simple
        filename: info.log
        maxBytes: 10485760 # 10MB
        backupCount: 20
        encoding: utf8

    error_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: ERROR
        formatter: simple
        filename: errors.log
        maxBytes: 10485760 # 10MB
        backupCount: 20
        encoding: utf8

    pub_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: INFO
        formatter: simple
        filename: pub_message.log
        maxBytes: 10485760 # 10MB
        backupCount: 20
        encoding: utf8

    sub_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: INFO
        formatter: simple
        filename: sub_message.log
        maxBytes: 10485760 # 10MB
        backupCount: 20
        encoding: utf8

loggers:
     sub:
        level: DEBUG
        handlers: [console,sub_file_handler]
     pub:
        level: DEBUG
        handlers: [console,pub_file_handler]
root:
    level: DEBUG
    handlers: [console, info_file_handler, error_file_handler]
